import {
  COLOR_BLACK,
  COLOR_DANGER,
  COLOR_GRAY_EXTRA_LIGHT,
  COLOR_HELP,
  COLOR_INFO,
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_SUCCESS,
  COLOR_WARNING,
  COLOR_WHITE,
} from "@constants/colors";

export const DIVIDER_COLOR_VARIANTS = {
  primary: COLOR_PRIMARY,
  secondary: COLOR_SECONDARY,
  success: COLOR_SUCCESS,
  warning: COLOR_WARNING,
  danger: COLOR_DANGER,
  info: COLOR_INFO,
  help: COLOR_HELP,
  white: COLOR_WHITE,
  black: COLOR_BLACK,
  grayExtraLight: COLOR_GRAY_EXTRA_LIGHT,
};
